export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const SIGN_UP = 'SIGN_UP'
export const RECOVER_PASSWORD = 'RECOVER_PASSWORD'

export const GET_ALL_PRODUTOS = 'GET_ALL_PRODUTOS'

export const NAVIGATE_MAIN_SCREEN = 'NAVIGATE_MAIN_SCREEN'
export const NAVIGATE_PRODUTO_SCREEN = 'NAVIGATE_PRODUTO_SCREEN'